// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect-four.proto

package connect_four_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartGameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c02c59e6b5c76743, []int{0}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

type StartGameResponse struct {
	Started              bool     `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameResponse) Reset()         { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string { return proto.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()    {}
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c02c59e6b5c76743, []int{1}
}

func (m *StartGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameResponse.Unmarshal(m, b)
}
func (m *StartGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameResponse.Marshal(b, m, deterministic)
}
func (m *StartGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameResponse.Merge(m, src)
}
func (m *StartGameResponse) XXX_Size() int {
	return xxx_messageInfo_StartGameResponse.Size(m)
}
func (m *StartGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameResponse proto.InternalMessageInfo

func (m *StartGameResponse) GetStarted() bool {
	if m != nil {
		return m.Started
	}
	return false
}

func (m *StartGameResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type MoveRequest struct {
	GameUuid             string   `protobuf:"bytes,1,opt,name=game_uuid,json=gameUuid,proto3" json:"game_uuid,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Player               int32    `protobuf:"varint,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c02c59e6b5c76743, []int{2}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetGameUuid() string {
	if m != nil {
		return m.GameUuid
	}
	return ""
}

func (m *MoveRequest) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

func (m *MoveRequest) GetPlayer() int32 {
	if m != nil {
		return m.Player
	}
	return 0
}

type MoveResponse struct {
	Board                []int32  `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`
	Winner               int32    `protobuf:"varint,2,opt,name=winner,proto3" json:"winner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c02c59e6b5c76743, []int{3}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetBoard() []int32 {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *MoveResponse) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func init() {
	proto.RegisterType((*StartGameRequest)(nil), "connect_four_proto.StartGameRequest")
	proto.RegisterType((*StartGameResponse)(nil), "connect_four_proto.StartGameResponse")
	proto.RegisterType((*MoveRequest)(nil), "connect_four_proto.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "connect_four_proto.MoveResponse")
}

func init() { proto.RegisterFile("connect-four.proto", fileDescriptor_c02c59e6b5c76743) }

var fileDescriptor_c02c59e6b5c76743 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0x8d, 0xbb, 0x5d, 0xb7, 0x6f, 0x3d, 0xe8, 0x43, 0xa4, 0xac, 0x07, 0x4b, 0x50, 0xe8,
	0xc5, 0x1e, 0xf4, 0xea, 0x45, 0x04, 0x3d, 0x88, 0x97, 0x88, 0x97, 0xbd, 0x94, 0x6c, 0x1b, 0xa5,
	0xb0, 0x4d, 0x6a, 0x9a, 0x28, 0x7e, 0x31, 0x3f, 0x9f, 0x24, 0xd9, 0xc8, 0xe2, 0x1f, 0xbc, 0x65,
	0x7e, 0xcc, 0x1b, 0x26, 0x03, 0x58, 0x2b, 0x29, 0x45, 0x6d, 0xce, 0x9e, 0x94, 0xd5, 0x65, 0xaf,
	0x95, 0x51, 0x18, 0x59, 0xe5, 0x58, 0xe5, 0x19, 0x45, 0xd8, 0x7b, 0x30, 0x5c, 0x9b, 0x5b, 0xde,
	0x09, 0x26, 0x5e, 0xac, 0x18, 0x0c, 0xbd, 0x82, 0xfd, 0x0d, 0x36, 0xf4, 0x4a, 0x0e, 0x02, 0x33,
	0xd8, 0x19, 0x1c, 0x14, 0x4d, 0x46, 0x72, 0x52, 0x4c, 0x59, 0x94, 0x88, 0x30, 0xb6, 0xb6, 0x6d,
	0xb2, 0xed, 0x9c, 0x14, 0x29, 0xf3, 0x6f, 0xba, 0x80, 0xd9, 0xbd, 0x7a, 0x8d, 0x89, 0x78, 0x04,
	0xe9, 0x33, 0xef, 0x44, 0xe5, 0x7d, 0xc4, 0xfb, 0xa6, 0x0e, 0x3c, 0xda, 0xb6, 0xc1, 0x43, 0x98,
	0xd4, 0x6a, 0x65, 0x3b, 0xe9, 0x13, 0x12, 0xb6, 0x56, 0x8e, 0xf7, 0x2b, 0xfe, 0x2e, 0x74, 0x36,
	0x0a, 0x3c, 0x28, 0x7a, 0x09, 0xbb, 0x21, 0x7b, 0xdd, 0xec, 0x00, 0x92, 0xa5, 0xe2, 0xda, 0x05,
	0x8f, 0x8a, 0x84, 0x05, 0xe1, 0xae, 0xdf, 0x5a, 0x29, 0x85, 0x8e, 0xa9, 0x41, 0x9d, 0x7f, 0x10,
	0x98, 0x5d, 0x87, 0x1d, 0x6e, 0x94, 0xd5, 0xb8, 0x80, 0xf4, 0xeb, 0xb3, 0x78, 0x52, 0xfe, 0x9c,
	0xa8, 0xfc, 0xbe, 0xcf, 0xfc, 0xf4, 0x1f, 0x57, 0xe8, 0x45, 0xb7, 0xf0, 0x0e, 0xc6, 0xae, 0x29,
	0x1e, 0xff, 0x76, 0xb0, 0xb1, 0xcf, 0x3c, 0xff, 0xdb, 0x10, 0xc3, 0x96, 0x13, 0x4f, 0x2f, 0x3e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x3d, 0x8b, 0x24, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectFourClient is the client API for ConnectFour service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectFourClient interface {
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
}

type connectFourClient struct {
	cc *grpc.ClientConn
}

func NewConnectFourClient(cc *grpc.ClientConn) ConnectFourClient {
	return &connectFourClient{cc}
}

func (c *connectFourClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, "/connect_four_proto.ConnectFour/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectFourClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/connect_four_proto.ConnectFour/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectFourServer is the server API for ConnectFour service.
type ConnectFourServer interface {
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
}

// UnimplementedConnectFourServer can be embedded to have forward compatible implementations.
type UnimplementedConnectFourServer struct {
}

func (*UnimplementedConnectFourServer) StartGame(ctx context.Context, req *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedConnectFourServer) Move(ctx context.Context, req *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}

func RegisterConnectFourServer(s *grpc.Server, srv ConnectFourServer) {
	s.RegisterService(&_ConnectFour_serviceDesc, srv)
}

func _ConnectFour_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectFourServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect_four_proto.ConnectFour/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectFourServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectFour_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectFourServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect_four_proto.ConnectFour/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectFourServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectFour_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connect_four_proto.ConnectFour",
	HandlerType: (*ConnectFourServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _ConnectFour_StartGame_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _ConnectFour_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect-four.proto",
}
